sources:
  - name: TokenSubgraph
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/43355/explorer-subgraph/v0.0.1

documents:
  - ./queries/tokens-by-users.graphql

    # transforms:
    #   - blockTracking:
    #     validateSchema: true

    # - autopagination:
    #     validateSchema: true
    #     limitOfRecords: 3000
# documents:
#   - ./queries/tokens-by-users.graphql
# plugins:
#   - pollingLive:
#       defaultInterval: 1000
