sources:
  - name: ETHRegistrarController
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/43355/ens-explorer/0.0.1

    transforms:
      - blockTracking:
        validateSchema: true

      - autopagination:
          validateSchema: true
          limitOfRecords: 3000

documents:
  - ./queries/ens-names-registered.graphql

plugins:
  - pollingLive:
      defaultInterval: 1000
